# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d983df7cb8c119f66d1e12a71510f45182c86b22df2a6a3558ed17bef0b88ca951b21389a8f560919a0caee196ee6462a99aeec26ece02cb138e9580c810f0

test:
  secret_key_base: 199cf4afe1ea84d5f6e5ec5d1c43a3da3c3c22fb865cc5febb370557f02a1e03b26f87b4c435a484856e232ce56af2d4dac0b8be8bad3f2beca294f5671e03da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
